apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: argo-app
  labels:
    app: nginx
    test: argo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8080
